apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: changeme
    jsonData:
      version: Flux
      organization: gradle
      defaultBucket: build-scans
      tlsSkipVerify: true
