{
 "title": "Build scans",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "taskName" },
   {
    "name": "taskType",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"build-scans\",\n    tag: \"taskType\",\n    predicate: (r) => true,\n    start: -30d\n)"
   }
  ]
 },
 "panels": [
  { "title": "Stats by task name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration by task name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \"${taskName}\" == \"All\" or r.taskName =~ /${taskName}/)\n  |> drop(columns: [\"avoidanceOutcome\", \"taskType\", \"taskName\", \"buildScanId\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"duration\")"
    }
   ]
  },
  {
   "title": "Execution distribution by task name",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \"${taskName}\" == \"All\" or r.taskName =~ /${taskName}/)\n  |> last()\n  |> group()\n  |> group(columns: [\"avoidanceOutcome\"])\n  |> count()\n  |> rename(columns: {_value: \"\"})"
    }
   ]
  },
  { "title": "Stats by task type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Duration by task type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: \"All\", set: ${taskType:json}) or contains(value: r.taskType, set: ${taskType:json}))\n  |> drop(columns: [\"avoidanceOutcome\", \"taskType\", \"taskName\", \"buildScanId\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> yield(name: \"duration\")"
    }
   ]
  },
  {
   "title": "Execution distribution by task type",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"build-scans\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: \"All\", set: ${taskType:json}) or contains(value: r.taskType, set: ${taskType:json}))\n  |> last()\n  |> group()\n  |> group(columns: [\"avoidanceOutcome\"])\n  |> count()\n  |> rename(columns: {_value: \"\"}) //remove _value from Pie slice naming\n"
    }
   ]
  }
 ]
}